name: dmr
version: 0.0.1
author: Harald Pehl <harald.pehl@gmail.com>
description: Dart library to execute operations on the JBoss AS7 DMR API.
homepage: https://github.com/hal/dmr.dart
documentation: http://hal.github.io/dmr.dart/
dependencies:
  browser: any
  meta: any
dev_dependencies:
  unittest: any
  hop: '>=0.21.0'
